### ISSUE TITLE
Road Map

### ISSUE THREAD

**Issue by granawkins** [AbanteAI/ragdaemon#1]
## Backend
1. Add chromadb / embeddings
2. Generate positions: filetree-spring & tsne
3. Add search route to backend

## Frontend
4. Refactor frontend components: global funcs passed to scene / controlPanel
5. Rebuild control panel to search / results
6. Update three to match latent-dictionary: transparency, camera movements

**Comment by tikimcfee** [comment]
Hey there! Love this project, I've got something similar I think. I'm curious if you'd like someone to help with anything on this list - any priority, something you'd like an extra pair of hands on, so to speak. Let me know - I'm happy to chat about your ideas and how you'd like things to work!

**Comment by granawkins** [comment]
Thanks! This is still in the really early stages so a bit early for contributions, but I will let you know when it gets there. Feel free to leave any feedback/comments you have, much appreciated 🙏
